services:
  - type: web
    name: freshkeep-api
    env: python
    buildCommand: "pip install -r requirements_prod.txt"
    startCommand: "python create_db.py && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0